const express = require('express');
const axios = require('axios');
const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');

const router = express.Router();

// Add GET route for clarity
router.get('/', (req, res) => {
  res.status(200).json({
    message: 'This endpoint only supports POST requests for AI book generation. Please use POST with a prompt.'
  });
});

// Helper to call internal endpoints
async function callInternal(endpoint, data) {
  return axios.post(`http://localhost:5000${endpoint}`, data, { timeout: 120000 });
}

router.post('/', async (req, res) => {
  const { prompt } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required.' });
  }

  try {
    // 1. Generate book structure (title, chapters, etc.)
    const textRes = await callInternal('/generate-text', { prompt });
    const bookText = textRes.data.text;
    // For demo, split into chapters by 'Chapter' keyword
    const chapters = bookText.split(/Chapter [0-9]+:/i).filter(Boolean);

    // 2. Generate images for each chapter
    const images = [];
    for (let i = 0; i < chapters.length; i++) {
      const imgPrompt = `Illustration for: ${chapters[i].slice(0, 100)}`;
      try {
        const imgRes = await callInternal('/generate-image', { prompt: imgPrompt });
        images.push(imgRes.data.imageUrl || imgRes.data.imageBase64 || null);
      } catch (e) {
        images.push(null);
      }
    }

    // 3. Compile PDF
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.TimesRoman);
    // Title page
    const titlePage = pdfDoc.addPage();
    titlePage.drawText('Your AI-Generated Book', {
      x: 50, y: 700, size: 32, font, color: rgb(0.2, 0.2, 0.7)
    });
    titlePage.drawText('Generated by LazyWrite', { x: 50, y: 650, size: 18, font, color: rgb(0.5, 0.5, 0.5) });
    // Chapters
    for (let idx = 0; idx < chapters.length; idx++) {
      const ch = chapters[idx];
      const page = pdfDoc.addPage();
      page.drawText(`Chapter ${idx + 1}`, { x: 50, y: 700, size: 24, font, color: rgb(0.1, 0.1, 0.1) });
      page.drawText(ch.slice(0, 1000), { x: 50, y: 650, size: 12, font, color: rgb(0, 0, 0) });
      // If image is base64, embed it
      if (images[idx] && images[idx].length > 100) {
        try {
          const imgBytes = Buffer.from(images[idx], 'base64');
          const img = await pdfDoc.embedPng(imgBytes);
          page.drawImage(img, { x: 50, y: 400, width: 200, height: 200 });
        } catch (e) {}
      }
    }
    const pdfBytes = await pdfDoc.save();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="book.pdf"');
    return res.send(Buffer.from(pdfBytes));
  } catch (error) {
    return res.status(500).json({ error: error.message });
  }
});

module.exports = router; 